# Generated by Django 3.1.6 on 2021-02-14 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
                ('location', models.TextField(blank=True)),
                ('term', models.CharField(blank=True, choices=[('Summer', 'summer'), ('Fall', 'fall'), ('IAP', 'iap'), ('Spring', 'spring')], max_length=10)),
                ('requirments', models.CharField(blank=True, choices=[('C++', 'c++'), ('Research', 'research'), ('Python', 'python'), ('MatLab', 'matlab'), ('3D Printing', '3d printing')], max_length=20)),
                ('prefences', models.CharField(blank=True, choices=[('C++', 'c++'), ('Research', 'research'), ('Python', 'python'), ('MatLab', 'matlab'), ('3D Printing', '3d printing')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
